### ISSUE TITLE
Setting up the project board

### ISSUE THREAD

**Issue by yahyaelganyni1** [AkashaRojee/marvel-api#21]
In this capstone project, we are 2 people.

[project board](https://github.com/AkashaRojee/js-capstone/projects/1)

**Comment by Davidosky007** [comment]
# Hi @yahyaelganyni1 @AkashaRojee 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```
